name: Basic FTP Deploy

on:
  workflow_dispatch: # Manual trigger only

jobs:
  basic-ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create netrc file for FTP authentication
        run: |
          echo "machine ftp.moahalksa.com login u142041678.moehl password q!!XE6HHYTqjbAL" > ~/.netrc
          chmod 600 ~/.netrc
      
      - name: Create file list
        run: |
          find . -type f -not -path "*/\.*" -not -path "*/node_modules/*" > files_to_upload.txt
      
      - name: Create deployment script
        run: |
          echo "#!/bin/bash" > deploy.sh
          echo "ftp -inv ftp.moahalksa.com << EOF" >> deploy.sh
          echo "user u142041678.moehl q!!XE6HHYTqjbAL" >> deploy.sh
          echo "binary" >> deploy.sh
          echo "cd /domains/moahalksa.com/public_html/wp-content/themes/moahal" >> deploy.sh
          echo "prompt" >> deploy.sh
          echo "mput *.php" >> deploy.sh
          echo "bye" >> deploy.sh
          echo "EOF" >> deploy.sh
          chmod +x deploy.sh
      
      - name: Deploy files
        run: |
          # Using the basic ftp command
          ./deploy.sh
      
      - name: Deployment status
        run: |
          echo "Deployment attempt completed"
          echo "Check the logs for any errors"
