name: Direct FTP Deploy

on:
  workflow_dispatch: # Manual trigger only

jobs:
  direct-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Direct FTP Deploy
        run: |
          lftp -c "set ftp:ssl-allow no; \
                  open -u u142041678.moehl,q!!XE6HHYTqjbAL ftp.moahalksa.com; \
                  lcd .; \
                  cd /domains/moahalksa.com/public_html/wp-content/themes/moahal; \
                  mirror --reverse \
                        --delete \
                        --exclude-glob .git/ \
                        --exclude-glob .github/ \
                        --exclude-glob node_modules/ \
                        --verbose \
                        --parallel=3 \
                        ./ ./"

      - name: Deployment status
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Deployment successful"
          else
            echo "❌ Deployment failed"
            exit 1
          fi
