name: Direct FTP Deploy

on:
  workflow_dispatch: # Manual trigger only

jobs:
  direct-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Direct FTP Deploy
        run: |
          # Debug connection
          echo "Trying to connect to FTP server..."
          # Try different credential formats and paths
          
          # First approach - using exact credentials from Hostinger
          echo "Approach 1: Using full domain path with standard credentials"
          lftp -d -c "set ftp:ssl-allow no; \
                  set net:timeout 10; \
                  set net:max-retries 2; \
                  set net:reconnect-interval-base 5; \
                  open ftp://u142041678.moehl:q!!XE6HHYTqjbAL@ftp.moahalksa.com; \
                  pwd; \
                  ls -la"
          
          # Second approach - using root level path
          echo "Approach 2: Using simplified path"
          lftp -d -c "set ftp:ssl-allow no; \
                  set net:timeout 10; \
                  set net:max-retries 2; \
                  set net:reconnect-interval-base 5; \
                  open -u u142041678.moehl,q!!XE6HHYTqjbAL ftp.moahalksa.com; \
                  pwd; \
                  ls -la; \
                  mkdir -p /domains/moahalksa.com/public_html/wp-content/themes/moahal/test-folder"
          
          # Third approach - actual deployment with simpler credentials
          echo "Approach 3: Deploying with simplified credentials"
          lftp -c "set ftp:ssl-allow no; \
                  set net:timeout 15; \
                  set net:max-retries 3; \
                  set net:reconnect-interval-base 5; \
                  open -u u142041678.moehl,q!!XE6HHYTqjbAL ftp.moahalksa.com; \
                  lcd .; \
                  cd /domains/moahalksa.com/public_html/wp-content/themes/moahal; \
                  mirror --reverse \
                        --delete \
                        --exclude-glob .git/ \
                        --exclude-glob .github/ \
                        --exclude-glob node_modules/ \
                        --verbose \
                        --parallel=1 \
                        ./ ./"

      - name: Deployment status
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Deployment successful"
          else
            echo "❌ Deployment failed"
            exit 1
          fi
