name: Deploy to Hostinger

on:
  push:
    branches:
      - main
      - master
      - production
      - feature/test-workflow # For testing the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, gd, xml, zip
          tools: composer

      - name: Install dependencies
        run: |
          if [ -f "composer.json" ]; then
            composer install --no-dev --optimize-autoloader
          fi
          
      - name: Build assets (if using npm/yarn)
        run: |
          if [ -f "package.json" ]; then
            npm install
            npm run build
          fi

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/wp-content/themes/moahal/
          dangerous-clean-slate: false
          exclude: |
            **/.git/**
            **/.github/**
            **/node_modules/**
            .gitignore
            README.md
            package-lock.json
            yarn.lock
            .env
            .env.example
            .DS_Store
